@echo off
chcp 65001 >nul
echo elimNMS Server Starting...
echo elimNMS 서버를 시작합니다...
cd /d "C:\Users\user\Downloads\elim-NMS\elimNMS-public"
echo Starting Flask application...
"C:\Users\user\Downloads\elim-NMS\.venv\Scripts\python.exe" app.py
echo.
echo Server has stopped. Press any key to exit...
pause >nul